# Generated by Django 4.2.6 on 2023-11-07 14:32

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=core.models.generate_unique_code, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.CharField(max_length=20)),
                ('issued_by', models.CharField(max_length=20)),
                ('book', models.CharField(max_length=20)),
                ('issued_on', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.SmallIntegerField(blank=True, choices=[(1, '1st sem'), (2, '2nd sem'), (3, '3rd sem'), (4, '4th sem'), (5, '5th sem'), (6, '6th sem'), (7, '7th sem'), (8, '8th sem')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_collected', models.IntegerField(default=0)),
                ('book_issued', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
