# Generated by Django 4.2.6 on 2023-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tag_book_alter_tag_issued_by_alter_tag_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
